import { DM_Sans } from "next/font/google";
import "./globals.css";

const play = DM_Sans({
  subsets: ["latin"],
  display: 'swap',
  weight: ['300', '400', '700', '900', '1000'],
});

export const metadata = {
  title: "Keval Gohil",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico?v=2'],
    apple: ['/apple-touch-icon.png?var=2'],
    shortcut: ['/apple-touch-icon.png']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={play.className}>
        <script src="https://smtpjs.com/v3/smtp.js"></script>
        {children}
      </body>
    </html>
  );
}
