import { Play } from "next/font/google";
import "./globals.css";

const play = Play({ 
  subsets: ["latin"], 
  display: 'swap', 
  weight: ['400', '700'], 
});

export const metadata = {
  title: "Keval Gohil",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon.ico?v=2'],
    apple:['/apple-touch-icon.png?var=2'],
    shortcut:['/apple-touch-icon.png'] 
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={play.className}>
        <script src="https://smtpjs.com/v3/smtp.js"></script>
        {children}
        </body>
    </html>
  );
}
